"""Builds the single unified docx shell used by every document type.

Replaces the five divergent .docx templates: cover page, Crave header, generated
footer, dynamic TOC field and consistent styles are all created in code, so all
document types are formatted identically.
"""
import os
import datetime

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT, WD_BREAK
from docx.enum.section import WD_SECTION
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

from .style import (ASSETS, BODY_FONT, HEADING_FONT, HEADING_COLOR, BODY_COLOR,
                    MUTED_COLOR, RULE_COLOR, BODY_SIZE, LINE_SPACING, PARA_SPACE_AFTER,
                    HEADING_SIZES, applyBaseStyles)

LOGO = os.path.join(ASSETS, "crave_logo.png")
FOOTER_TEXT = "Generated by coreassess.ai"


def _field(paragraph, instruction):
    run = paragraph.add_run()
    begin = OxmlElement('w:fldChar'); begin.set(qn('w:fldCharType'), 'begin'); begin.set(qn('w:dirty'), 'true')
    instr = OxmlElement('w:instrText'); instr.set(qn('xml:space'), 'preserve'); instr.text = instruction
    sep = OxmlElement('w:fldChar'); sep.set(qn('w:fldCharType'), 'separate')
    placeholder = OxmlElement('w:t'); placeholder.text = "Update field (F9)"
    end = OxmlElement('w:fldChar'); end.set(qn('w:fldCharType'), 'end')
    for el in (begin, instr, sep, placeholder, end):
        run._r.append(el)
    return run


def _bottom_rule(paragraph, color=RULE_COLOR):
    pPr = paragraph._p.get_or_add_pPr()
    borders = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single'); bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '4'); bottom.set(qn('w:color'), color)
    borders.append(bottom)
    pPr.append(borders)


def _buildHeader(section, doc_title):
    header = section.header
    header.is_linked_to_previous = False
    para = header.paragraphs[0]
    para.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT
    usable = section.page_width - section.left_margin - section.right_margin
    _setTabs(para, [], right_at=usable)
    if os.path.exists(LOGO):
        para.add_run().add_picture(LOGO, height=Inches(0.22))
    tab = para.add_run("\t" + doc_title)
    tab.font.name = BODY_FONT
    tab.font.size = Pt(8.5)
    tab.font.color.rgb = MUTED_COLOR
    _bottom_rule(para)


# Page number left, generation note right (tab stop at the right margin).
def _buildFooter(section):
    footer = section.footer
    footer.is_linked_to_previous = False
    para = footer.paragraphs[0]
    para.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT
    usable = section.page_width - section.left_margin - section.right_margin
    _setTabs(para, [], right_at=usable)
    _field(para, ' PAGE ')
    para.add_run("\t" + FOOTER_TEXT)
    for run in para.runs:
        run.font.name = BODY_FONT
        run.font.size = Pt(8)
        run.font.color.rgb = MUTED_COLOR


def _coverPage(doc, meta):
    for _ in range(4):
        doc.add_paragraph()
    if os.path.exists(LOGO):
        logo_para = doc.add_paragraph()
        logo_para.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT
        logo_para.add_run().add_picture(LOGO, height=Inches(0.42))
        logo_para.paragraph_format.space_after = Pt(28)

    title = doc.add_paragraph()
    run = title.add_run(meta["doc_title"])
    run.font.name = HEADING_FONT; run.font.size = Pt(30); run.bold = True
    run.font.color.rgb = HEADING_COLOR
    title.paragraph_format.space_after = Pt(4)

    subtitle = doc.add_paragraph()
    sub = subtitle.add_run(meta["object_name"])
    sub.font.name = HEADING_FONT; sub.font.size = Pt(16)
    sub.font.color.rgb = MUTED_COLOR
    subtitle.paragraph_format.space_after = Pt(24)
    _bottom_rule(subtitle)

    for label, value in meta["fields"]:
        line = doc.add_paragraph()
        line.paragraph_format.space_after = Pt(3)
        key = line.add_run(f"{label}\t")
        key.font.name = BODY_FONT; key.font.size = Pt(9.5); key.font.color.rgb = MUTED_COLOR
        val = line.add_run(str(value))
        val.font.name = BODY_FONT; val.font.size = Pt(9.5); val.bold = True
        val.font.color.rgb = BODY_COLOR
        _setTabs(line, [Inches(1.9)])


def _setTabs(paragraph, positions, right_at=None):
    pPr = paragraph._p.get_or_add_pPr()
    tabs = OxmlElement('w:tabs')
    for pos in positions:
        tab = OxmlElement('w:tab')
        tab.set(qn('w:val'), 'left')
        tab.set(qn('w:pos'), str(int(pos.twips)))
        tabs.append(tab)
    if right_at is not None:
        tab = OxmlElement('w:tab')
        tab.set(qn('w:val'), 'right')
        twips = right_at.twips if hasattr(right_at, 'twips') else int(right_at / 635)
        tab.set(qn('w:pos'), str(int(twips)))
        tabs.append(tab)
    pPr.append(tabs)


def _tocPage(doc, depth=3):
    heading = doc.add_paragraph()
    run = heading.add_run("Contents")
    run.font.name = HEADING_FONT; run.font.size = Pt(HEADING_SIZES[1]); run.bold = True
    run.font.color.rgb = HEADING_COLOR
    heading.paragraph_format.space_after = Pt(10)

    para = doc.add_paragraph()
    _field(para, f' TOC \\o "1-{depth}" \\h \\z \\u ')

    # updateFields makes Word rebuild the TOC on open instead of showing a stale one.
    settings = doc.settings.element
    if settings.find(qn('w:updateFields')) is None:
        el = OxmlElement('w:updateFields')
        el.set(qn('w:val'), 'true')
        settings.append(el)


def buildShell(doc_title, object_name, company, project, approach="", depth=3):
    """Cover page + header/footer + dynamic TOC. Body is appended by the renderer."""
    doc = Document()
    applyBaseStyles(doc)

    section = doc.sections[0]
    section.top_margin = Inches(0.9)
    section.bottom_margin = Inches(0.9)
    section.left_margin = Inches(1.0)
    section.right_margin = Inches(1.0)
    section.header_distance = Inches(0.45)
    section.footer_distance = Inches(0.4)

    _buildHeader(section, doc_title)
    _buildFooter(section)

    fields = [("Company", company), ("Project", project), ("Object", object_name)]
    if approach:
        fields.append(("Approach", approach))
    fields.append(("Generated", datetime.date.today().isoformat()))
    _coverPage(doc, {"doc_title": doc_title, "object_name": object_name, "fields": fields})

    doc.add_page_break()
    _tocPage(doc, depth)
    doc.add_page_break()
    return doc
